[package]
name = "euler-rust"
version = "0.1.0"
authors = ["Paulo Elienay <elie9alb@gmail.com> @paulo-e"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
