[package]
name = "euler-rust"
version = "0.1.0"
authors = ["Alex Andrade Albuquerque <alex@alexaa.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
